### ISSUE TITLE
colors.scss ignores custom color setting

### ISSUE THREAD

**Issue by git-no** [mdbootstrap/bootstrap-material-design#29]
Colors setting are broken after update to latest MDB release.
Scenario: I have a separate custom.scss with variable declarartions, loaded before mdb.scss.
Two issues: pre set color variable are ignored and oversteered by MDB.

## !default missing
This is how it is (from one item example from _colors.scss):
```scss
...
$primary-color: #4285F4;
...
```

This is it how it **shoud be**:
```scss
...
$primary-color: #4285F4 !default;
...
```

## Variable missing
Also it would be a better approach to set colors by variables. This would simplify changing the colors of an color-variable would change the color allover the color-variable is used. I think this was already in previously releases. Don't know why that approach was dropped.

This is how it is (from one item example from _colors.scss):
```scss
...
.primary-color {
    background-color: #4285F4!important;
}
...
```

This is it how it **shoud be**
```scss
...
.primary-color {
    background-color: $primary-color !important;
}
...
```

**Comment by mattonit** [comment]
Thanks for noticing. We'll fix it

**Comment by git-no** [comment]
Hint: just let 
```scss
$mdb-color: #45526E;
.mdb-color {
    background-color: #45526E!important;
}
```
otherwise the file would fail compiling.
