### ISSUE TITLE
li without bullets issue

### ISSUE THREAD

**Issue by git-no** [mdbootstrap/bootstrap-material-design#30]
**Problem**: lists are without bullet by default in MDB.
**Reason**: is within _global.scss: 
```scss
ul {
    padding: 0;
    list-style-type: none;
    li {
        list-style-type: none;
    }
}
````

**Required**: list should have bullets by default!

**Solution**: every developer can achieve lists without bullets by simly adding the Bootstrap class ```class="list-unstyled"``` to the ```<ul>```tag.
As described in [Bootstrap documentation](http://v4-alpha.getbootstrap.com/content/typography/#unstyled)

This should be getting fixed in MDB.
