### ISSUE TITLE
MDB does not display .sticky

### ISSUE THREAD

**Issue by git-no** [mdbootstrap/bootstrap-material-design#36]
Elements with class sticky are not displayed on smaller devices < 768px.
This is wrong.

Reason:
scrollspy.scss
```css
@media only screen and (max-width: 769px) {
    .sticky,
    .sticky-placeholder {
        display: none; 
    }
}
```

Solution:
Restrict your css code by adding id or class rules for your scrollspy so .sticky display none has no inpact of .sticky use in other code areas. Thank you.

The same for all other .sticky style modifications in your scss files. Please don't define it general make it more specific (add classes or id). Something like this 
```css
@media only screen and (min-width: 1200px) {
    .col-md-4 .sticky {
        width: 300px;
    }
}
```
has impact on all pages :-(
